config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  devise_for :users

  root to: 'pages#home'

  resources :task_templates do
    post 'create_task', to: 'task_templates#create_task_from_template', as: 'create_task'
  end

  resources :tasks do
    resources :subtasks do
      patch :toggle_completed
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task

  validates :content, presence: true
  validates :content, length: { minimum: 2 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :subtasks, dependent: :destroy

  validates :title, presence: true
  validates :title, length: { minimum: 2 }
end

app/models/task_template.rb
class TaskTemplate < ApplicationRecord
  belongs_to :user
  has_many :subtask_templates

  validates :title, presence: true, length: { minimum: 2 }
  validates :category, presence: true, length: { minimum: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks

  validates :email, format: { with: /\A(\S+)@(([a-z]{3,})\.([a-z]{2,}))\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :find_task, only: %i[new create edit]
  before_action :set_subtask, only: %i[edit update destroy]

  def new
    @subtask = Subtask.new
  end

  def create
    @subtask = Subtask.new(subtask_params)
    @subtask.task = @task
    if @subtask.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @subtask.update(subtask_params)
    redirect_to tasks_path
  end

  def destroy
    @subtask.destroy
    redirect_to tasks_path
  end

  def toggle_completed
    @subtask = Subtask.find(params[:subtask_id])
    @subtask.update(completed: !@subtask.completed)
    toggle_task_completed(@subtask)
    redirect_to tasks_path
  end

  private

  def set_subtask
    @subtask = Subtask.find(params[:id])
  end

  def find_task
    @task = Task.find(params[:task_id])
  end

  def subtask_params
    params.require(:subtask).permit(:content)
  end

  def toggle_task_completed(subtask)
    @task = subtask.task
    @task.subtasks.map(&:completed).all? { |e| e == true } ? @task.update(completed: true, finished_at: Time.now) : @task.update(completed: false, finished_at: nil)
  end
end

app/controllers/task_templates_controller.rb
class TaskTemplatesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task_template, only: %i[show edit update destroy create_task_from_template]

  def index
    @task_templates = TaskTemplate.where(user: current_user)
  end

  def show; end

  def new
    @task_template = TaskTemplate.new
  end

  def create
    @task_template = TaskTemplate.new(task_template_params)
    params[:task_template][:subtasks].split(";").each do |subtask|
      @task_template.subtasks << subtask
    end
    @task_template.user = current_user
    if @task_template.save
      redirect_to task_templates_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task_template.update(task_template_params)
      redirect_to task_templates_path
    else
      render :edit
    end
  end

  def destroy
    @task_template.destroy
    redirect_to task_templates_path
  end

  def create_task_from_template
    task = Task.create(title: @task_template.title, category: @task_template.category, user: current_user)
    @task_template.subtasks.each do |subtask_template|
      subtask = Subtask.new(content: subtask_template)
      subtask.task_id = task.id
      subtask.save
    end
    redirect_to tasks_path
  end

  private

  def set_task_template
    @task_template = TaskTemplate.find(params[:id] || params[:task_template_id])
  end

  def task_template_params
    params.require(:task_template).permit(:title, :category)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @pending_tasks = Task.where(user: current_user, finished_at: nil)
    @finished_tasks = Task.where(user: current_user).where.not(finished_at: nil)
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Reculist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content flex">
      <%= render 'shared/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row align-items-center">
    <div id="logo" class="col-12 mb-5 col-lg-8 order-lg-1 mb-lg-0">
      <%= image_tag("home.svg", alt: "home banner") %>
    </div>
    <div class="col-12 col-lg-4">
      <h2>Gérez vos listes de tâches simplement</h2>
      <%= link_to  "Accéder à mes tâches", tasks_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white mb-5">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>Reculist</h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item">
          <%= link_to  "Mes templates", task_templates_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to  "Mes listes", tasks_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <!--<%= link_to  "Timeline", root_path, class: "nav-link" %>-->
          <a class="nav-link" href="#">Timeline</a>
        </li>
      </ul>
    </div>
    <div class="collapse navbar-collapse justify-content-end" id="navbarToggler">
      <% if current_user %>
        <%= link_to  "Mon compte", edit_user_registration_path %>
      <% else %>
        <%= link_to  "Se connecter", new_user_session_path %>
      <% end %>
    </div>
  </div>
</nav>

app/views/subtasks/_form.html.erb
<%= simple_form_for [@task, @subtask] do |f| %>
  <%= f.input :content, label: "Contenu" %>
  <div class="form-row">
    <div class="col-6">
      <%= link_to  "Retour", tasks_path, class: "btn btn-warning" %>
    </div>
    <div class="col-6">
      <%= f.button :submit, "Confirmer", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-6">
      <div class="forms">
        <h2>Editer la sous-tâche "<%= @subtask.content %>"</h2>

        <%= render  "form" %>
      </div>
    </div>
  </div>
</div>

app/views/subtasks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-6">
      <div class="forms">
        <h2>Nouvelle sous-tâche pour "<%= @task.title %>"</h2>

        <%= render  "form" %>
      </div>
    </div>
  </div>
</div>

app/views/task_templates/_form.html.erb
<%= simple_form_for @task_template do |f| %>
  <%= f.input :title, label: "Titre" %>
  <%= f.input :category, label: "Categorie" %>
  <%= f.input :subtasks, label: "Sous-tâches (séparer par ';')", multiple: true %>
  
  <div class="form-row">
    <div class="col-6">
      <%= link_to  "Retour", task_templates_path, class: "btn btn-warning" %>
    </div>
    <div class="col-6">
      <%= f.button :submit, "Confirmer", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/task_templates/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-6">
      <div class="forms">
        <h2>Modifier le template "<%= @task_template.title %>"</h2>

        <%= render  "form" %>
      </div>
    </div>
  </div>
</div>

app/views/task_templates/index.html.erb
<div class="container">
  <div class="d-flex align-items-center mb-3">
    <h2 class="mr-3">Mes templates</h2>
    <%= link_to  icon('fas', 'plus', 'Ajouter'), new_task_template_path %>
  </div>

  <% @task_templates.each do |task_template| %>
    <div class="card mb-4">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <div class="flex-grow-1">
            <h3><%= task_template.title %></h3>
          </div>
          <div>
            <%= link_to  "Start a task with this template", task_template_create_task_path(task_template), method: :post %>
            <%= link_to icon('fas', 'edit'), edit_task_template_path(task_template) %>
            <%= link_to icon('fas', 'times'), task_template_path(task_template) , method: :delete, data: { confirm: "Supprimer la tâche ?"}, class: 'delete-icon' %>
          </div>
        </div>
      </div>
      <div class="card-body list-group list-group-flush py-2 px-3">
        <% task_template.subtasks.each do |subtask| %>
          <div class="d-flex list-group-item">
            <div class="flex-grow-1">
              <p class="my-1"><%= subtask %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/task_templates/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-6">
      <div class="forms">
        <h2>Nouvelle tâche</h2>

        <%= render  "form" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :title, label: "Titre" %>
  <%= f.input :category, label: "Categorie" %>
  <div class="form-row">
    <div class="col-6">
      <%= link_to  "Retour", tasks_path, class: "btn btn-warning" %>
    </div>
    <div class="col-6">
      <%= f.button :submit, "Confirmer", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-10 col-lg-6">
      <div class="forms">
        <h2>Modifier la tâche "<%= @task.title %>"</h2>

        <%= render  "form" %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="d-flex align-items-center mb-3">
    <h2 class="mr-3">En cours</h2>
  </div>
  <% @pending_tasks.each do |task| %>
    <div class="card mb-4">
      <div class="card-header">
        <div class="d-flex align-items-center">
          <div class="mr-3">
            <%= task.completed ? icon('fas', 'check-square') : icon('far', 'square') %>
          </div>
          <div class="flex-grow-1">
            <h3><%= task.title %></h3>
          </div>
          <div>
            <%= link_to icon('fas', 'edit'), edit_task_path(task) %>
            <%= link_to icon('fas', 'times'), task_path(task) , method: :delete, data: { confirm: "Supprimer la tâche ?"}, class: 'delete-icon' %>
          </div>
        </div>
      </div>
      <div class="card-body list-group list-group-flush py-2 px-3">
        <% task.subtasks.order("id").each do |subtask| %>
          <div class="d-flex list-group-item">
            <div class="mx-3 d-flex align-items-center">
              <% if subtask.completed %>
                <%= link_to icon('fas', 'check-square'), task_subtask_toggle_completed_path(task, subtask), method: :patch, class: "mark_uncompleted" %>
              <% else %>
                <%= link_to icon('far', 'square'), task_subtask_toggle_completed_path(task, subtask), method: :patch, class: "mark_completed" %>
              <% end %>
            </div>
            <div class="flex-grow-1">
              <p class="my-1"><%= subtask.content %></p>
            </div>
            <div>
              <%= link_to icon('fas', 'edit'), edit_task_subtask_path(task, subtask) %>
              <%= link_to icon('fas', 'times'), task_subtask_path(task, subtask) , method: :delete, data: { confirm: "Supprimer la sous-tâche ?"} %>
            </div>
          </div>
        <% end %>
        <div class="add-subtask list-group-item mx-3">
          <%= link_to icon('fas', 'plus', 'Ajouter une sous-tâche', class: "icon-mr"), new_task_subtask_path(task.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <% unless @finished_tasks.empty? %>
    <div class="d-flex align-items-center mb-3">
      <h2 class="mr-3">Terminés</h2>
    </div>
    <% @finished_tasks.each do |task| %>
      <div class="card mb-4">
        <div class="card-header">
          <div class="d-flex align-items-center">
            <div class="mr-3">
              <%= icon('fas', 'check-square') %>
            </div>
            <div class="flex-grow-1 d-flex justify-content-between align-items-center">
              <h3><%= task.title %></h3>
              <p class="m-0">Terminée le: <%= task.finished_at.utc.localtime.strftime("%d/%m/%Y - %H:%M") %></p>
            </div>
          </div>
        </div>
        <div class="card-body list-group list-group-flush py-2 px-3">
          <% task.subtasks.order("id").each do |subtask| %>
            <div class="d-flex list-group-item">
              <div class="mx-3 d-flex align-items-center">
                <% if subtask.completed %>
                  <%= link_to icon('fas', 'check-square'), task_subtask_toggle_completed_path(task, subtask), method: :patch, class: "mark_uncompleted" %>
                <% else %>
                  <%= link_to icon('far', 'square'), task_subtask_toggle_completed_path(task, subtask), method: :patch, class: "mark_completed" %>
                <% end %>
              </div>
              <div class="flex-grow-1">
                <p class="my-1"><%= subtask.content %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>